### ISSUE TITLE
Ability to exclude vendor mapping

### ISSUE THREAD

**Issue by srosato** [Webonaute/DoctrineFixturesGeneratorBundle#41]
I have the following configuration:

```
entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
```

But it throws

```
[LogicException]
  No bundle found for entity namespace Gedmo\Translatable\Entity
```
I have to comment the `gedmo_translatable` section for now, since I have not yet translated my database.

I know it is said that vendor entities are not supported yet, but how can I ignore that mapping for now without commenting, since I cannot use an annotation to ignore it?

Of course I am left wondering how I will be able to reverse translations in the future, but I guess this is another issue!
